#
# Executes commands at the start of an interactive session.
#

# PowerLevel9K font
POWERLEVEL9K_MODE='nerdfont-complete'

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Enable Custom theme only on Terminal.app
if [[ "$TERM_PROGRAM" == "Apple_Terminal" ]]; then

  # Enable Theme powerlevel9k
  prompt powerlevel9k
  POWERLEVEL9K_SHORTEN_STRATEGY="truncate_to_unique"
  POWERLEVEL9K_SHORTEN_DIR_LENGTH=1

  POWERLEVEL9K_DIR_SHOW_WRITABLE=true
  POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=1
  POWERLEVEL9K_STATUS_OK=false
  POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true
  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator ssh os_icon dir vcs)
  POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time)
  POWERLEVEL9K_DIR_PATH_SEPARATOR=" $(print_icon "LEFT_SUBSEGMENT_SEPARATOR") "
  POWERLEVEL9K_HOME_FOLDER_ABBREVIATION="%F{red} $(print_icon 'HOME_ICON') %F{black}"
fi

# Customize to your needs...
dsh() {
  echo "Logging into $1...";
  docker exec -it $1 sh;
}

# Alias
alias d=docker
alias gs="git status"
alias gco="git checkout"
alias gpo="git pull origin"
alias gpu="git push origin"

# Use IntelliJ's bundled JDK + maven
export JAVA_HOME="/Applications/IntelliJ IDEA CE.app/Contents/jbr/Contents/Home"

function mvn() {
  java -Dmaven.multiModuleProjectDirectory=`pwd` \
   "-Dmaven.home=/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3" \
   "-Dclassworlds.conf=/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/bin/m2.conf" \
   -Dfile.encoding=UTF-8 \
   -classpath "/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.5.2.jar" \
   org.codehaus.classworlds.Launcher $*
}

